{% set name = "pyamg" %}
{% set version = "4.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 37ad3c1dcaff2435c2ab7c8ec36942af0726c563d35059bcd18eb07473f7182e

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pybind11
    - setuptools_scm
    # setuptools_scm[toml] requires:
    - setuptools >=42
    - pip
  run:
    - {{ pin_compatible("numpy") }}
    - python
    - scipy >=0.12.0

test:
  requires:
    - pip
    - pytest
  imports:
    - pyamg
  commands:
    - pip check

about:
  home: https://github.com/pyamg/pyamg
  license: MIT
  license_file: LICENSE.txt
  summary: Algebraic Multigrid Solvers in Python

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
    - xylar
