{% set name = "pyamg" %}
{% set version = "5.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f449d934224e503401ee72cd2eece1a29d893b7abe35f62a44d52ba831198efa

build:
  number: 1
  script: {{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pybind11 >=2.12.0
    - setuptools_scm >=7.0.0
    # explicit requirement and also required by setuptools_scm[toml]:
    - setuptools >=42
    - pip
  run:
    - python
    - scipy >=1.11.0

test:
  requires:
    - pip
    - pytest
  imports:
    - pyamg
  commands:
    - pip check

about:
  home: https://github.com/pyamg/pyamg
  license: MIT
  license_file: LICENSE.txt
  summary: Algebraic Multigrid Solvers in Python

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
    - xylar
