{% set name = "pyamg" %}
{% set version = "5.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eab967228f614342ce23c7b4d6bbca25ad8b927a45cb7626d1ef17c9f062a02e

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pybind11 >=2.8.0
    - setuptools_scm >=7.0.0
    # explicit requirement and also required by setuptools_scm[toml]:
    - setuptools >=42
    - pip
  run:
    - {{ pin_compatible("numpy") }}
    - python
    - scipy >=0.12.0

test:
  requires:
    - pip
    - pytest
  imports:
    - pyamg
  commands:
    - pip check

about:
  home: https://github.com/pyamg/pyamg
  license: MIT
  license_file: LICENSE.txt
  summary: Algebraic Multigrid Solvers in Python

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
    - xylar
