{% set name = "pyamg" %}
{% set version = "4.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4cacfcfd13379762a4551ac059a2e52a093b476ca1ad44b9202e736490a8863
  patches:
    - 0001-remove-unneeded-requirement.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pybind11
    - setuptools
    - pip
  run:
    - {{ pin_compatible("numpy") }}
    - python
    - scipy

test:
  requires:
    - pytest
    - pip
  imports:
    - pyamg
  commands:
    - pip check

about:
  home: https://github.com/pyamg/pyamg
  license: MIT
  license_file: LICENSE.txt
  summary: Algebraic Multigrid Solvers in Python

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
    - xylar
