{% set name = "pyamg" %}
{% set version = "4.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0845fdd4b96fc45cbd04f5a6ff4a1b9bfd671ad69ef80898431c8d03b75ad6d
  patches:
    - 0001-remove-unneeded-requirement.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - pybind11
    - setuptools_scm
    # setuptools_scm[toml] requires:
    - setuptools >=42
    - pip
  run:
    - {{ pin_compatible("numpy") }}
    - python
    - scipy >=0.12.0

test:
  requires:
    - pytest
    - pip
  imports:
    - pyamg
  commands:
    - pip check

about:
  home: https://github.com/pyamg/pyamg
  license: MIT
  license_file: LICENSE.txt
  summary: Algebraic Multigrid Solvers in Python

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
    - xylar
