{% set name = "pyamg" %}
{% set version = "4.0.0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 3ceb38ffd86e29774e759486f2961599c8ed847459c68727493cadeaf115a38a

build:
    number: 1000
    script: "{{ PYTHON }} -m pip install . -vv"
    skip: True   # [win and vc<14]
    skip: True   # [osx and c_compiler == 'toolchain_c']

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - python
        - numpy
        - pybind11
        - setuptools
        - pip
    run:
        - {{ pin_compatible("numpy") }}
        - python
        - scipy

test:
    requires:
        - pytest
    imports:
        - pyamg

about:
    home: https://github.com/pyamg/pyamg
    license: MIT
    license_file: LICENSE.txt
    summary: "Algebraic Multigrid Solvers in Python"

extra:
  recipe-maintainers:
    - jakevdp
    - lukeolson
