appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qtgJkqFNobBh1ikxhcntjOtMNeuj4jxx/ZzVyADNxOOAX6yQx8hMMy3zhRV3lmUDMkze1yPCQkYGpZmkLQlJfTLVQz0KWxRpWj0lTJ8IV/hTZQWSfBpDhpxpd1V/KtPVDTIw5oXB153RTzPj2LXsZHwzDlOA5T+92qbPNNbADg8Ie2OqgOjSyhfG+HPmrYR7zS2z58V1jCTeD8wTGBvr4EPTaJ0xrlZWYflB56XWPvro/ElDo/cjNuAuAz5PcRgF4cWi6ZaTdqj9orablcMNrwDY545n/Ir+jHyUdIkGWAweOZNVP0dFNHdc1/zDTHe1itq2xSghw/W2rULDmkvWMFLf3r4xXUuJrBwthYeONiqnXRO3Z5ZHjD82wkCgNwoOsgF1CPzrpnhXNisYEF6kezTebyhNJW/Zvf8AApOuRjdhxnHg/OK6wuCHO8Zyu7091hppTm9SmNvCB5NkUx6ef1h4rXdGKRE9At2CCEUPx3IeWPmEpcM3hgnVBRujgzvmWzx64N3k7l7gaw/Fj7T7fE7h5u0VPQttJeSYeS+QsHiXCzkVdHxPsqNenUy8B5vsj9OBJl3+R5L7pOM+989XdfLhU0O89DR3CSX216zHQtWj8MRuJQs1E2C9xHIVe/kGNxt47QScaDTuHZB30RWopBB0rjfjlWOF5FNU1jrmh0o=}
provider:
  win: azure
